package com.fet.telemedicine.backend.repository.pgsql.po;
// Generated 2022/5/31 �U�� 04:54:49 by Hibernate Tools 5.3.15.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;


/**
 * Account generated by hbm2java
 */
@Entity
public class Account implements java.io.Serializable {
    @Id
    private int id;
    private String username;
    private String password;
    private String salt;
    private Integer status;
    private Integer valid;
    private Date activateTime;
    private String createdBy;
    private Date createdTime;
    private String updatedBy;
    private Date updatedTime;

    public Account() {
    }

    public Account(int id, String username) {
	this.id = id;
	this.username = username;
    }

    public Account(int id, String username, String password, String salt, Integer status, Integer valid,
	    Date activateTime, String createdBy, Date createdTime, String updatedBy, Date updatedTime) {
	this.id = id;
	this.username = username;
	this.password = password;
	this.salt = salt;
	this.status = status;
	this.valid = valid;
	this.activateTime = activateTime;
	this.createdBy = createdBy;
	this.createdTime = createdTime;
	this.updatedBy = updatedBy;
	this.updatedTime = updatedTime;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public String getUsername() {
	return this.username;
    }

    public void setUsername(String username) {
	this.username = username;
    }

    public String getPassword() {
	return this.password;
    }

    public void setPassword(String password) {
	this.password = password;
    }

    public String getSalt() {
	return this.salt;
    }

    public void setSalt(String salt) {
	this.salt = salt;
    }

    public Integer getStatus() {
	return this.status;
    }

    public void setStatus(Integer status) {
	this.status = status;
    }

    public Integer getValid() {
	return this.valid;
    }

    public void setValid(Integer valid) {
	this.valid = valid;
    }

    public Date getActivateTime() {
	return this.activateTime;
    }

    public void setActivateTime(Date activateTime) {
	this.activateTime = activateTime;
    }

    public String getCreatedBy() {
	return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
	return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
	return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public Date getUpdatedTime() {
	return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
    }

}
