package com.fet.telemedicine.backend.repository.pgsql.po;
// Generated 2022/5/31 �U�� 04:54:49 by Hibernate Tools 5.3.15.Final

import java.util.Date;

/**
 * Appointment generated by hbm2java
 */
public class Appointment implements java.io.Serializable {

    private int id;
    private int type;
    private int doctorUserId;
    private int patientUserId;
    private int outpatientId;
    private Integer signupSeq;
    private String memo;
    private String vhcToken;
    private Integer status;
    private int meetingId;
    private String createdBy;
    private Date createdTime;
    private String updatedBy;
    private Date updatedTime;

    public Appointment() {
    }

    public Appointment(int id, int type, int doctorUserId, int patientUserId, int outpatientId, int meetingId) {
	this.id = id;
	this.type = type;
	this.doctorUserId = doctorUserId;
	this.patientUserId = patientUserId;
	this.outpatientId = outpatientId;
	this.meetingId = meetingId;
    }

    public Appointment(int id, int type, int doctorUserId, int patientUserId, int outpatientId, Integer signupSeq,
	    String memo, String vhcToken, Integer status, int meetingId, String createdBy, Date createdTime,
	    String updatedBy, Date updatedTime) {
	this.id = id;
	this.type = type;
	this.doctorUserId = doctorUserId;
	this.patientUserId = patientUserId;
	this.outpatientId = outpatientId;
	this.signupSeq = signupSeq;
	this.memo = memo;
	this.vhcToken = vhcToken;
	this.status = status;
	this.meetingId = meetingId;
	this.createdBy = createdBy;
	this.createdTime = createdTime;
	this.updatedBy = updatedBy;
	this.updatedTime = updatedTime;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public int getType() {
	return this.type;
    }

    public void setType(int type) {
	this.type = type;
    }

    public int getDoctorUserId() {
	return this.doctorUserId;
    }

    public void setDoctorUserId(int doctorUserId) {
	this.doctorUserId = doctorUserId;
    }

    public int getPatientUserId() {
	return this.patientUserId;
    }

    public void setPatientUserId(int patientUserId) {
	this.patientUserId = patientUserId;
    }

    public int getOutpatientId() {
	return this.outpatientId;
    }

    public void setOutpatientId(int outpatientId) {
	this.outpatientId = outpatientId;
    }

    public Integer getSignupSeq() {
	return this.signupSeq;
    }

    public void setSignupSeq(Integer signupSeq) {
	this.signupSeq = signupSeq;
    }

    public String getMemo() {
	return this.memo;
    }

    public void setMemo(String memo) {
	this.memo = memo;
    }

    public String getVhcToken() {
	return this.vhcToken;
    }

    public void setVhcToken(String vhcToken) {
	this.vhcToken = vhcToken;
    }

    public Integer getStatus() {
	return this.status;
    }

    public void setStatus(Integer status) {
	this.status = status;
    }

    public int getMeetingId() {
	return this.meetingId;
    }

    public void setMeetingId(int meetingId) {
	this.meetingId = meetingId;
    }

    public String getCreatedBy() {
	return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
	return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
	return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public Date getUpdatedTime() {
	return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
    }

}
