package com.fet.telemedicine.backend.repository.pgsql.po;
// Generated 2022/5/31 �U�� 04:54:49 by Hibernate Tools 5.3.15.Final

import java.util.Date;

/**
 * CompanySetting generated by hbm2java
 */
public class CompanySetting implements java.io.Serializable {

    private int id;
    private int companyId;
    private Integer accountLimit;
    private Integer outpatientLimit;
    private Integer enableOpenAppointment;
    private Integer enableSyncAppointment;
    private Integer syncAppointmentDays;
    private String createdBy;
    private Date createdTime;
    private String updatedBy;
    private Date updatedTime;

    public CompanySetting() {
    }

    public CompanySetting(int id, int companyId) {
	this.id = id;
	this.companyId = companyId;
    }

    public CompanySetting(int id, int companyId, Integer accountLimit, Integer outpatientLimit,
	    Integer enableOpenAppointment, Integer enableSyncAppointment, Integer syncAppointmentDays, String createdBy,
	    Date createdTime, String updatedBy, Date updatedTime) {
	this.id = id;
	this.companyId = companyId;
	this.accountLimit = accountLimit;
	this.outpatientLimit = outpatientLimit;
	this.enableOpenAppointment = enableOpenAppointment;
	this.enableSyncAppointment = enableSyncAppointment;
	this.syncAppointmentDays = syncAppointmentDays;
	this.createdBy = createdBy;
	this.createdTime = createdTime;
	this.updatedBy = updatedBy;
	this.updatedTime = updatedTime;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public int getCompanyId() {
	return this.companyId;
    }

    public void setCompanyId(int companyId) {
	this.companyId = companyId;
    }

    public Integer getAccountLimit() {
	return this.accountLimit;
    }

    public void setAccountLimit(Integer accountLimit) {
	this.accountLimit = accountLimit;
    }

    public Integer getOutpatientLimit() {
	return this.outpatientLimit;
    }

    public void setOutpatientLimit(Integer outpatientLimit) {
	this.outpatientLimit = outpatientLimit;
    }

    public Integer getEnableOpenAppointment() {
	return this.enableOpenAppointment;
    }

    public void setEnableOpenAppointment(Integer enableOpenAppointment) {
	this.enableOpenAppointment = enableOpenAppointment;
    }

    public Integer getEnableSyncAppointment() {
	return this.enableSyncAppointment;
    }

    public void setEnableSyncAppointment(Integer enableSyncAppointment) {
	this.enableSyncAppointment = enableSyncAppointment;
    }

    public Integer getSyncAppointmentDays() {
	return this.syncAppointmentDays;
    }

    public void setSyncAppointmentDays(Integer syncAppointmentDays) {
	this.syncAppointmentDays = syncAppointmentDays;
    }

    public String getCreatedBy() {
	return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
	return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
	return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public Date getUpdatedTime() {
	return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
    }

}
