package com.fet.telemedicine.backend.repository.pgsql.po;
// Generated 2022/5/31 �U�� 04:54:49 by Hibernate Tools 5.3.15.Final

import java.util.Date;

/**
 * Contract generated by hbm2java
 */
public class Contract implements java.io.Serializable {

    private int id;
    private String version;
    private int companySettingId;
    private String name;
    private String documentUrl;
    private String createdBy;
    private Date createdTime;
    private String updatedBy;
    private Date updatedTime;

    public Contract() {
    }

    public Contract(int id, int companySettingId, String name, String documentUrl) {
	this.id = id;
	this.companySettingId = companySettingId;
	this.name = name;
	this.documentUrl = documentUrl;
    }

    public Contract(int id, int companySettingId, String name, String documentUrl, String createdBy, Date createdTime,
	    String updatedBy, Date updatedTime) {
	this.id = id;
	this.companySettingId = companySettingId;
	this.name = name;
	this.documentUrl = documentUrl;
	this.createdBy = createdBy;
	this.createdTime = createdTime;
	this.updatedBy = updatedBy;
	this.updatedTime = updatedTime;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public String getVersion() {
	return this.version;
    }

    public void setVersion(String version) {
	this.version = version;
    }

    public int getCompanySettingId() {
	return this.companySettingId;
    }

    public void setCompanySettingId(int companySettingId) {
	this.companySettingId = companySettingId;
    }

    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public String getDocumentUrl() {
	return this.documentUrl;
    }

    public void setDocumentUrl(String documentUrl) {
	this.documentUrl = documentUrl;
    }

    public String getCreatedBy() {
	return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
	return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
	return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public Date getUpdatedTime() {
	return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
    }

}
