package com.fet.telemedicine.backend.repository.pgsql.po;
// Generated 2022/5/31 �U�� 04:54:49 by Hibernate Tools 5.3.15.Final

import java.util.Date;

/**
 * Dept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

    private int id;
    private String name;
    private String code;
    private int companyId;
    private String brief;
    private String createdBy;
    private Date createdTime;
    private String updatedBy;
    private Date updatedTime;

    public Dept() {
    }

    public Dept(int id, int companyId) {
	this.id = id;
	this.companyId = companyId;
    }

    public Dept(int id, String name, String code, int companyId, String brief, String createdBy, Date createdTime,
	    String updatedBy, Date updatedTime) {
	this.id = id;
	this.name = name;
	this.code = code;
	this.companyId = companyId;
	this.brief = brief;
	this.createdBy = createdBy;
	this.createdTime = createdTime;
	this.updatedBy = updatedBy;
	this.updatedTime = updatedTime;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public String getCode() {
	return this.code;
    }

    public void setCode(String code) {
	this.code = code;
    }

    public int getCompanyId() {
	return this.companyId;
    }

    public void setCompanyId(int companyId) {
	this.companyId = companyId;
    }

    public String getBrief() {
	return this.brief;
    }

    public void setBrief(String brief) {
	this.brief = brief;
    }

    public String getCreatedBy() {
	return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
	return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
	return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public Date getUpdatedTime() {
	return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
    }

}
