package com.fet.telemedicine.backend.repository.pgsql.po;
// Generated 2022/5/31 �U�� 04:54:49 by Hibernate Tools 5.3.15.Final

import java.util.Date;

/**
 * Meeting generated by hbm2java
 */
public class Meeting implements java.io.Serializable {

    private int id;
    private int vidyoId;
    private String createdBy;
    private Date createdTime;
    private String updatedBy;
    private Date updatedTime;

    public Meeting() {
    }

    public Meeting(int id, int vidyoId) {
	this.id = id;
	this.vidyoId = vidyoId;
    }

    public Meeting(int id, int vidyoId, String createdBy, Date createdTime, String updatedBy, Date updatedTime) {
	this.id = id;
	this.vidyoId = vidyoId;
	this.createdBy = createdBy;
	this.createdTime = createdTime;
	this.updatedBy = updatedBy;
	this.updatedTime = updatedTime;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public int getVidyoId() {
	return this.vidyoId;
    }

    public void setVidyoId(int vidyoId) {
	this.vidyoId = vidyoId;
    }

    public String getCreatedBy() {
	return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
	return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
	return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public Date getUpdatedTime() {
	return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
    }

}
