package com.fet.telemedicine.backend.repository.pgsql.po;
// Generated 2022/5/31 �U�� 04:54:49 by Hibernate Tools 5.3.15.Final

import java.util.Date;

/**
 * Outpatient generated by hbm2java
 */
public class Outpatient implements java.io.Serializable {

    private int id;
    private int deptId;
    private String code;
    private String roomNo;
    private String paymentTool;
    private int doctorUserId;
    private int nurseUserId;
    private Integer status;
    private Integer numberLimit;
    private Integer currentSignupCnt;
    private Date startTime;
    private Date endTime;
    private Integer outOfQuota;
    private String createdBy;
    private Date createdTime;
    private String updatedBy;
    private Date updatedTime;

    public Outpatient() {
    }

    public Outpatient(int id, int deptId, String code, int doctorUserId, int nurseUserId) {
	this.id = id;
	this.deptId = deptId;
	this.code = code;
	this.doctorUserId = doctorUserId;
	this.nurseUserId = nurseUserId;
    }

    public Outpatient(int id, int deptId, String code, String roomNo, String paymentTool, int doctorUserId,
	    int nurseUserId, Integer status, Integer numberLimit, Integer currentSignupCnt, Date startTime,
	    Date endTime, Integer outOfQuota, String createdBy, Date createdTime, String updatedBy, Date updatedTime) {
	this.id = id;
	this.deptId = deptId;
	this.code = code;
	this.roomNo = roomNo;
	this.paymentTool = paymentTool;
	this.doctorUserId = doctorUserId;
	this.nurseUserId = nurseUserId;
	this.status = status;
	this.numberLimit = numberLimit;
	this.currentSignupCnt = currentSignupCnt;
	this.startTime = startTime;
	this.endTime = endTime;
	this.outOfQuota = outOfQuota;
	this.createdBy = createdBy;
	this.createdTime = createdTime;
	this.updatedBy = updatedBy;
	this.updatedTime = updatedTime;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public int getDeptId() {
	return this.deptId;
    }

    public void setDeptId(int deptId) {
	this.deptId = deptId;
    }

    public String getCode() {
	return this.code;
    }

    public void setCode(String code) {
	this.code = code;
    }

    public String getRoomNo() {
	return this.roomNo;
    }

    public void setRoomNo(String roomNo) {
	this.roomNo = roomNo;
    }

    public String getPaymentTool() {
	return this.paymentTool;
    }

    public void setPaymentTool(String paymentTool) {
	this.paymentTool = paymentTool;
    }

    public int getDoctorUserId() {
	return this.doctorUserId;
    }

    public void setDoctorUserId(int doctorUserId) {
	this.doctorUserId = doctorUserId;
    }

    public int getNurseUserId() {
	return this.nurseUserId;
    }

    public void setNurseUserId(int nurseUserId) {
	this.nurseUserId = nurseUserId;
    }

    public Integer getStatus() {
	return this.status;
    }

    public void setStatus(Integer status) {
	this.status = status;
    }

    public Integer getNumberLimit() {
	return this.numberLimit;
    }

    public void setNumberLimit(Integer numberLimit) {
	this.numberLimit = numberLimit;
    }

    public Integer getCurrentSignupCnt() {
	return this.currentSignupCnt;
    }

    public void setCurrentSignupCnt(Integer currentSignupCnt) {
	this.currentSignupCnt = currentSignupCnt;
    }

    public Date getStartTime() {
	return this.startTime;
    }

    public void setStartTime(Date startTime) {
	this.startTime = startTime;
    }

    public Date getEndTime() {
	return this.endTime;
    }

    public void setEndTime(Date endTime) {
	this.endTime = endTime;
    }

    public Integer getOutOfQuota() {
	return this.outOfQuota;
    }

    public void setOutOfQuota(Integer outOfQuota) {
	this.outOfQuota = outOfQuota;
    }

    public String getCreatedBy() {
	return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
	return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
	return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public Date getUpdatedTime() {
	return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
    }

}
