package com.fet.telemedicine.backend.repository.pgsql.po;
// Generated 2022/5/31 �U�� 04:54:49 by Hibernate Tools 5.3.15.Final

import java.util.Date;

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

    private int id;
    private int userId;
    private int roleId;
    private String createdBy;
    private Date createdTime;
    private String updatedBy;
    private Date updatedTime;

    public UserRole() {
    }

    public UserRole(int id, int userId, int roleId) {
	this.id = id;
	this.userId = userId;
	this.roleId = roleId;
    }

    public UserRole(int id, int userId, int roleId, String createdBy, Date createdTime, String updatedBy,
	    Date updatedTime) {
	this.id = id;
	this.userId = userId;
	this.roleId = roleId;
	this.createdBy = createdBy;
	this.createdTime = createdTime;
	this.updatedBy = updatedBy;
	this.updatedTime = updatedTime;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public int getUserId() {
	return this.userId;
    }

    public void setUserId(int userId) {
	this.userId = userId;
    }

    public int getRoleId() {
	return this.roleId;
    }

    public void setRoleId(int roleId) {
	this.roleId = roleId;
    }

    public String getCreatedBy() {
	return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
	return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
	return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public Date getUpdatedTime() {
	return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
    }

}
