package com.fet.telemedicine.backend.repository.pgsql.po;
// Generated 2022/5/31 �U�� 04:54:49 by Hibernate Tools 5.3.15.Final

import java.util.Date;

/**
 * UserAppInfo generated by hbm2java
 */
public class UserAppInfo implements java.io.Serializable {

    private int id;
    private int userId;
    private String platform;
    private String appType;
    private String appName;
    private String appVersion;
    private String createdBy;
    private Date createdTime;
    private String updatedBy;
    private Date updatedTime;

    public UserAppInfo() {
    }

    public UserAppInfo(int id, int userId, String platform, String appType, String appName, String appVersion) {
	this.id = id;
	this.userId = userId;
	this.platform = platform;
	this.appType = appType;
	this.appName = appName;
	this.appVersion = appVersion;
    }

    public UserAppInfo(int id, int userId, String platform, String appType, String appName, String appVersion,
	    String createdBy, Date createdTime, String updatedBy, Date updatedTime) {
	this.id = id;
	this.userId = userId;
	this.platform = platform;
	this.appType = appType;
	this.appName = appName;
	this.appVersion = appVersion;
	this.createdBy = createdBy;
	this.createdTime = createdTime;
	this.updatedBy = updatedBy;
	this.updatedTime = updatedTime;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public int getUserId() {
	return this.userId;
    }

    public void setUserId(int userId) {
	this.userId = userId;
    }

    public String getPlatform() {
	return this.platform;
    }

    public void setPlatform(String platform) {
	this.platform = platform;
    }

    public String getAppType() {
	return this.appType;
    }

    public void setAppType(String appType) {
	this.appType = appType;
    }

    public String getAppName() {
	return this.appName;
    }

    public void setAppName(String appName) {
	this.appName = appName;
    }

    public String getAppVersion() {
	return this.appVersion;
    }

    public void setAppVersion(String appVersion) {
	this.appVersion = appVersion;
    }

    public String getCreatedBy() {
	return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
	return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
	return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public Date getUpdatedTime() {
	return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
    }

}
