package com.fet.telemedicine.backend.repository.pgsql.po;
// Generated 2022/5/31 �U�� 04:54:49 by Hibernate Tools 5.3.15.Final

import java.util.Date;

/**
 * UserAuth generated by hbm2java
 */
public class UserAuth implements java.io.Serializable {

    private int id;
    private int userId;
    private String tokenType;
    private String tokenValue;
    private String verifyCode;
    private String createdBy;
    private Date createdTime;
    private String updatedBy;
    private Date updatedTime;

    public UserAuth() {
    }

    public UserAuth(int id, int userId) {
	this.id = id;
	this.userId = userId;
    }

    public UserAuth(int id, int userId, String tokenType, String tokenValue, String verifyCode, String createdBy,
	    Date createdTime, String updatedBy, Date updatedTime) {
	this.id = id;
	this.userId = userId;
	this.tokenType = tokenType;
	this.tokenValue = tokenValue;
	this.verifyCode = verifyCode;
	this.createdBy = createdBy;
	this.createdTime = createdTime;
	this.updatedBy = updatedBy;
	this.updatedTime = updatedTime;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public int getUserId() {
	return this.userId;
    }

    public void setUserId(int userId) {
	this.userId = userId;
    }

    public String getTokenType() {
	return this.tokenType;
    }

    public void setTokenType(String tokenType) {
	this.tokenType = tokenType;
    }

    public String getTokenValue() {
	return this.tokenValue;
    }

    public void setTokenValue(String tokenValue) {
	this.tokenValue = tokenValue;
    }

    public String getVerifyCode() {
	return this.verifyCode;
    }

    public void setVerifyCode(String verifyCode) {
	this.verifyCode = verifyCode;
    }

    public String getCreatedBy() {
	return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
	return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
	return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public Date getUpdatedTime() {
	return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
    }

}
