package com.fet.telemedicine.backend.repository.pgsql.po;
// Generated 2022/5/31 �U�� 04:54:49 by Hibernate Tools 5.3.15.Final

import java.util.Date;

/**
 * UserSetting generated by hbm2java
 */
public class UserSetting implements java.io.Serializable {

    private int id;
    private int userId;
    private Integer enableNotification;
    private Integer enableCalling;
    private String createdBy;
    private Date createdTime;
    private String updatedBy;
    private Date updatedTime;

    public UserSetting() {
    }

    public UserSetting(int id, int userId) {
	this.id = id;
	this.userId = userId;
    }

    public UserSetting(int id, int userId, Integer enableNotification, Integer enableCalling, String createdBy,
	    Date createdTime, String updatedBy, Date updatedTime) {
	this.id = id;
	this.userId = userId;
	this.enableNotification = enableNotification;
	this.enableCalling = enableCalling;
	this.createdBy = createdBy;
	this.createdTime = createdTime;
	this.updatedBy = updatedBy;
	this.updatedTime = updatedTime;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public int getUserId() {
	return this.userId;
    }

    public void setUserId(int userId) {
	this.userId = userId;
    }

    public Integer getEnableNotification() {
	return this.enableNotification;
    }

    public void setEnableNotification(Integer enableNotification) {
	this.enableNotification = enableNotification;
    }

    public Integer getEnableCalling() {
	return this.enableCalling;
    }

    public void setEnableCalling(Integer enableCalling) {
	this.enableCalling = enableCalling;
    }

    public String getCreatedBy() {
	return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
	return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
	return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public Date getUpdatedTime() {
	return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
    }

}
