package com.fet.telemedicine.backend.repository.pgsql.po;
// Generated 2022/5/31 �U�� 04:54:49 by Hibernate Tools 5.3.15.Final

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private int id;
    private String type;
    private String name;
    private String nickname;
    private String avatar;
    private String email;
    private String mobile;
    private String gender;
    private String birthday;
    private String brief;
    private String address;
    private String staffCode;
    private Integer status;
    private Integer online;
    private Integer identitytype;
    private String identityno;
    private int deptId;
    private int accountId;
    private String createdBy;
    private Date createdTime;
    private String updatedBy;
    private Date updatedTime;

    public User() {
    }

    public User(int id, String name, int deptId, int accountId) {
	this.id = id;
	this.name = name;
	this.deptId = deptId;
	this.accountId = accountId;
    }

    public User(int id, String type, String name, String nickname, String avatar, String email, String mobile,
	    String gender, String birthday, String brief, String address, String staffCode, Integer status,
	    Integer online, Integer identitytype, String identityno, int deptId, int accountId, String createdBy,
	    Date createdTime, String updatedBy, Date updatedTime) {
	this.id = id;
	this.type = type;
	this.name = name;
	this.nickname = nickname;
	this.avatar = avatar;
	this.email = email;
	this.mobile = mobile;
	this.gender = gender;
	this.birthday = birthday;
	this.brief = brief;
	this.address = address;
	this.staffCode = staffCode;
	this.status = status;
	this.online = online;
	this.identitytype = identitytype;
	this.identityno = identityno;
	this.deptId = deptId;
	this.accountId = accountId;
	this.createdBy = createdBy;
	this.createdTime = createdTime;
	this.updatedBy = updatedBy;
	this.updatedTime = updatedTime;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public String getType() {
	return this.type;
    }

    public void setType(String type) {
	this.type = type;
    }

    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public String getNickname() {
	return this.nickname;
    }

    public void setNickname(String nickname) {
	this.nickname = nickname;
    }

    public String getAvatar() {
	return this.avatar;
    }

    public void setAvatar(String avatar) {
	this.avatar = avatar;
    }

    public String getEmail() {
	return this.email;
    }

    public void setEmail(String email) {
	this.email = email;
    }

    public String getMobile() {
	return this.mobile;
    }

    public void setMobile(String mobile) {
	this.mobile = mobile;
    }

    public String getGender() {
	return this.gender;
    }

    public void setGender(String gender) {
	this.gender = gender;
    }

    public String getBirthday() {
	return this.birthday;
    }

    public void setBirthday(String birthday) {
	this.birthday = birthday;
    }

    public String getBrief() {
	return this.brief;
    }

    public void setBrief(String brief) {
	this.brief = brief;
    }

    public String getAddress() {
	return this.address;
    }

    public void setAddress(String address) {
	this.address = address;
    }

    public String getStaffCode() {
	return this.staffCode;
    }

    public void setStaffCode(String staffCode) {
	this.staffCode = staffCode;
    }

    public Integer getStatus() {
	return this.status;
    }

    public void setStatus(Integer status) {
	this.status = status;
    }

    public Integer getOnline() {
	return this.online;
    }

    public void setOnline(Integer online) {
	this.online = online;
    }

    public Integer getIdentitytype() {
	return this.identitytype;
    }

    public void setIdentitytype(Integer identitytype) {
	this.identitytype = identitytype;
    }

    public String getIdentityno() {
	return this.identityno;
    }

    public void setIdentityno(String identityno) {
	this.identityno = identityno;
    }

    public int getDeptId() {
	return this.deptId;
    }

    public void setDeptId(int deptId) {
	this.deptId = deptId;
    }

    public int getAccountId() {
	return this.accountId;
    }

    public void setAccountId(int accountId) {
	this.accountId = accountId;
    }

    public String getCreatedBy() {
	return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
	this.createdBy = createdBy;
    }

    public Date getCreatedTime() {
	return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
	return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
	this.updatedBy = updatedBy;
    }

    public Date getUpdatedTime() {
	return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
    }

}
